THEMENAME = "beginnerluftclassic"

FONT = "Georgia"
FONT_SIZE_XXXL = 96
FONT_SIZE_XXL = 64
FONT_SIZE_XL = 48
FONT_SIZE_L = 32
FONT_SIZE_M = 24
FONT_SIZE_S = 16
FONT_SIZE_XS = 14
FONT_SIZE_XXS = 10

HEADING_BOOTSTYLE = ""
HOVER_BOOTSTYLE = "info"
SELECTION_BOOTSTYLE = "primary"
